/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlacesIndexImport } from './routes/places/index'
import { Route as PlacesPlaceIdImport } from './routes/places/$placeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlacesIndexRoute = PlacesIndexImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRoute,
} as any)

const PlacesPlaceIdRoute = PlacesPlaceIdImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdImport
      parentRoute: typeof rootRoute
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places': typeof PlacesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places': typeof PlacesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places/': typeof PlacesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/places/$placeId' | '/places'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/places/$placeId' | '/places'
  id: '__root__' | '/' | '/places/$placeId' | '/places/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/places/$placeId",
        "/places/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/places/$placeId": {
      "filePath": "places/$placeId.tsx"
    },
    "/places/": {
      "filePath": "places/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
